pick_up_position:
  tx: 2.0
  ty: 0.0
  tz: 0.0
  quat_x: 0.0
  quat_y: 0.0
  quat_z: 0.0
  quat_w: 2.0

drop_off_position:
  tx: 5.0
  ty: 1.0
  tz: 0.0
  quat_x: 0.0
  quat_y: 0.0
  quat_z: 0.0
  quat_w: 2.0
